name: build-windows-exe

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install .
          python -m pip install pyinstaller
      - name: Build exe
        run: |
          pyinstaller --onefile -n video-summary \
            --collect-all whisper --collect-all torch --collect-all openai \
            --hidden-import=tqdm --hidden-import=rich \
            src/video_summary/cli.py
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: video-summary-windows
          path: dist/video-summary.exe

